import React, { createContext, useContext, useState, useCallback } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa', flag: '🇳🇬' },
  { code: 'ig', name: 'Igbo', nativeName: 'Igbo', flag: '🇳🇬' },
  { code: 'ff', name: 'Fulfude', nativeName: 'Fulfulde', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
];

// Complete translations for all supported languages
export const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    home: 'Home',
    features: 'Features',
    assessment: 'Risk Assessment',
    devices: 'Wearables',
    telemedicine: 'Telemedicine',
    education: 'Education Hub',
    login: 'Sign In',
    register: 'Sign Up',
    logout: 'Logout',
    profile: 'Profile',
    admin: 'Admin Dashboard',
    
    // Hero
    heroTitle: 'Mamacare',
    heroSubtitle: 'AI-powered maternal health companion',
    heroBody: 'Empowering every mother with intelligent risk assessment, personalized guidance, and 24/7 support throughout the journey of motherhood.',
    startJourney: 'Start Your Journey',
    learnMore: 'Learn More',
    
    // Stats
    aiAccuracy: 'AI Accuracy',
    languages: 'Languages',
    support: 'Support',
    mothersHelped: 'Mothers Helped',
    
    // Features
    comprehensiveCare: 'Comprehensive Care',
    careSubtitle: 'Everything you need for a healthy pregnancy',
    aiAssessment: 'AI Risk Assessment',
    aiAssessmentDesc: 'Real-time analysis of vital signs using advanced LightGBM machine learning models with 84% accuracy',
    telemedicineTitle: 'Telemedicine',
    telemedicineDesc: 'Connect with maternal health specialists instantly via video or chat consultation',
    educationHub: 'Education Hub',
    educationHubDesc: 'Evidence-based maternal health guides, nutrition tips, and personalized recommendations',
    
    // How It Works
    howItWorks: 'How MamaCare Works',
    step1Title: 'Enter Your Vitals',
    step1Desc: 'Input your health data manually or connect with wearable devices for continuous monitoring',
    step2Title: 'AI Analysis',
    step2Desc: 'Our LightGBM model analyzes your risk factors with 84% accuracy and SHAP explainability',
    step3Title: 'Get Insights',
    step3Desc: 'Receive personalized recommendations, alerts, and connect with healthcare providers',
    
    // Risk Assessment
    checkRisk: 'Check Your Risk Level',
    assessmentSubtitle: 'Enter your vital signs for an AI-powered risk assessment based on clinical research',
    age: 'Age (years)',
    systolicBP: 'Systolic BP (mmHg)',
    diastolicBP: 'Diastolic BP (mmHg)',
    bloodSugar: 'Blood Sugar (mmol/L)',
    bodyTemp: 'Body Temperature (°C)',
    heartRate: 'Heart Rate (bpm)',
    getAssessment: 'Get Assessment',
    analyzing: 'Analyzing...',
    
    // Risk Results
    riskAssessmentResult: 'Risk Assessment Result',
    confidenceScore: 'Confidence Score',
    keyFactors: 'Key Risk Factors',
    recommendations: 'Recommendations',
    normalRange: 'All vitals within normal range',
    
    // Risk Levels
    lowRisk: 'Low Risk',
    mediumRisk: 'Medium Risk',
    highRisk: 'High Risk',
    lowRiskDesc: 'Your vitals are within healthy ranges. Continue regular checkups.',
    mediumRiskDesc: 'Some factors need attention. Schedule a consultation soon.',
    highRiskDesc: 'Immediate medical attention recommended. Contact your healthcare provider.',
    
    // SHAP Analysis
    aiModelInsights: 'AI Model Insights (SHAP Analysis)',
    bloodSugarImportance: 'Blood Sugar - Strongest predictor of maternal risk',
    ageImportance: 'Age - Maternal age affects pregnancy outcomes',
    heartRateImportance: 'Heart Rate - Cardiovascular stress indicator',
    
    // Risk Assessment - Symptoms & Notes
    currentSymptoms: 'Current Symptoms',
    selectSymptoms: 'Select any symptoms you are currently experiencing',
    additionalNotes: 'Additional Notes',
    pastAssessments: 'Past Assessments',
    noPastAssessments: 'No past assessments yet',
    
    // Wearables
    futureMonitoring: 'Future of Monitoring',
    wearablesSubtitle: 'Conceptual African-themed wearable devices for continuous maternal health monitoring',
    guardianWatch: 'Guardian Watch',
    guardianWatchDesc: 'Continuous vital tracking with African-inspired design elements',
    unityBand: 'Unity Band',
    unityBandDesc: 'Activity and sleep monitoring for holistic wellness tracking',
    serenityNecklace: 'Serenity Necklace',
    serenityNecklaceDesc: 'Elegant stress and wellness tracking with mindfulness features',
    vitalityRing: 'Vitality Ring',
    vitalityRingDesc: 'Discrete 24/7 health monitoring in a beautiful ring design',
    keyFeatures: 'Key Features',
    comingSoon: 'Coming Soon',
    
    // Telemedicine
    connectExperts: 'Connect With Experts',
    telemedicineSubtitle: 'Instant access to certified maternal health specialists',
    videoConsult: 'Video Consultations',
    videoConsultDesc: 'Face-to-face consultations with maternal health specialists from the comfort of your home',
    chatSupport: 'Chat Support',
    chatSupportDesc: '24/7 chat support for immediate health concerns and questions',
    appointmentBooking: 'Appointment Booking',
    appointmentBookingDesc: 'Easy scheduling for in-person visits and follow-up consultations',
    ourDoctors: 'Our Healthcare Providers',
    bookAppointment: 'Book Appointment',
    available: 'Available',
    unavailable: 'Unavailable',
    nextAvailable: 'Next Available',
    viewProfile: 'View Profile',
    specialty: 'Specialty',
    languagesSpoken: 'Languages',
    rating: 'Rating',
    reviews: 'reviews',
    
    // Education Hub
    educationTitle: 'Maternal Health Education',
    educationSubtitle: 'Evidence-based resources for every stage of your pregnancy journey',
    nutrition: 'Nutrition & Diet',
    exercise: 'Exercise & Fitness',
    mentalHealth: 'Mental Health',
    prenatalCare: 'Prenatal Care',
    postnatalCare: 'Postnatal Care',
    newbornCare: 'Newborn Care',
    readMore: 'Read More',
    
    // Auth
    welcomeBack: 'Welcome Back',
    signInToContinue: 'Sign in to continue your maternal health journey',
    email: 'Email Address',
    password: 'Password',
    phone: 'Phone Number',
    name: 'Full Name',
    forgotPassword: 'Forgot Password?',
    orContinueWith: 'Or continue with',
    signInWithGoogle: 'Sign in with Google',
    signInWithPhone: 'Sign in with Phone',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    agreeTerms: 'I agree to the Terms of Service and Privacy Policy',
    
    // Profile
    myProfile: 'My Profile',
    personalInfo: 'Personal Information',
    pregnancyInfo: 'Pregnancy Information',
    assessmentHistory: 'Assessment History',
    myAppointments: 'My Appointments',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    dueDate: 'Expected Due Date',
    bloodType: 'Blood Type',
    allergies: 'Allergies',
    medications: 'Current Medications',
    
    // Admin
    dashboard: 'Dashboard',
    users: 'Users',
    records: 'Records',
    doctors: 'Doctors',
    content: 'Content',
    settings: 'Settings',
    totalUsers: 'Total Users',
    totalAssessments: 'Total Assessments',
    totalDoctors: 'Total Doctors',
    totalAppointments: 'Total Appointments',
    riskDistribution: 'Risk Distribution',
    recentActivity: 'Recent Activity',
    addDoctor: 'Add Doctor',
    editDoctor: 'Edit Doctor',
    deleteDoctor: 'Delete Doctor',
    
    // Footer
    footerTagline: 'AI-powered maternal health companion empowering mothers across Africa and beyond.',
    quickLinks: 'Quick Links',
    resources: 'Resources',
    contact: 'Contact',
    supportEmail: 'support@mamacare.app',
    supportPhone: '+234 800 MAMACARE',
    location: 'Lagos, Nigeria',
    rights: 'All rights reserved.',
    researchBy: 'Research by Idris Olanrewaju Ibraheem et al.',
    
    // Testimonials
    whatMothersSay: 'What Mothers Say',
    
    // FAQ
    commonQuestions: 'Common Questions',
    
    // CTA
    startToday: 'Start Your Journey Today',
    ctaSubtitle: 'Join thousands of mothers who trust MamaCare for their maternal health journey',
    downloadApp: 'Download MamaCare',
    
    // Emergency
    emergency: 'Emergency',
    emergencyTitle: 'Emergency Services',
    emergencySubtitle: 'Get help immediately',
    requestAmbulance: 'Request Ambulance',
    ambulanceDesc: 'Your location will be shared with emergency services',
    requesting: 'Requesting...',
    callAmbulance: 'Call Ambulance Now',
    emergencyContacts: 'Emergency Contacts',
    note: 'Note',
    emergencyNote: 'In case of life-threatening emergency, call your local emergency number immediately.',
  },
  
  // Yoruba
  yo: {
    home: 'Ile',
    features: 'Awọn ohun elo',
    assessment: 'Iṣiro Ewu',
    devices: 'Awọn ẹrọ',
    telemedicine: 'Telemedicine',
    education: 'Ile-iwe Eko',
    login: 'Wole',
    register: 'Forukọsilẹ',
    logout: 'Jade',
    profile: 'Profaili',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Olùbátan ilera ìyá alágbára AI',
    heroBody: 'Fun gbogbo ìyá ní agbára pẹlu iwadi ewu ọgbọn, itọsọna ti ara ẹni, ati atilẹyin 24/7 nipasẹ irin ajo ìyá.',
    startJourney: 'Bẹrọ Irin ajo Rẹ',
    learnMore: 'Kọ ẹkọ diẹ sii',
    
    aiAccuracy: 'AI Dájú',
    languages: 'Awọn ede',
    support: 'Atilẹyin',
    
    comprehensiveCare: 'Itọju Pipe',
    careSubtitle: 'Gbogbo ohun ti o nilo fun alaboyun ni ilera',
    aiAssessment: 'Iwadi Ewu AI',
    aiAssessmentDesc: 'Atunyẹwo awọn aami iye ni akoko gangan lilo awọn aṣa ẹkọ ijinlẹ LightGBM ilọsiwaju',
    telemedicineTitle: 'Telemedicine',
    telemedicineDesc: 'So pọ mọ awọn onímọ ẹ̀kọ́ ilera ìyá ni kia kia nipasẹ fidio tabi ìfọ̀rọ̀wánilẹ́nuwò',
    educationHub: 'Ile-iwe Eko',
    educationHubDesc: 'Awọn itọsọna ilera ìyá ti o da lori ẹri, awọn imọran oúnjẹ, ati awọn imọran ti ara ẹni',
    
    howItWorks: 'Bí MamaCare Ṣe Nṣiṣẹ́',
    step1Title: 'Tẹ Awọn Aami Iye Rẹ',
    step1Desc: 'Tẹ data ilera rẹ ni ọwọ tabi so pọ mọ awọn ẹrọ ti a lọwọ fun atunyẹwo ti o tẹsiwaju',
    step2Title: 'Atunyẹwo AI',
    step2Desc: 'Aṣa wa LightGBM ṣe atunyẹwo awọn idi ewu rẹ pẹlu dájú 84% ati SHAP alaye',
    step3Title: 'Gba Awọn Oye',
    step3Desc: 'Gba awọn imọran ti ara ẹni, awọn ikilọ, ati so pọ mọ awọn olupese ilera',
    
    checkRisk: 'Ṣayẹwo Ipele Ewu Rẹ',
    age: 'Ọjọ ori (ọdún)',
    systolicBP: 'Systolic BP (mmHg)',
    diastolicBP: 'Diastolic BP (mmHg)',
    bloodSugar: 'Sokiri ẹjẹ (mmol/L)',
    bodyTemp: 'Iwọn otutu ara (°C)',
    heartRate: 'Iṣẹ ọkan (bpm)',
    getAssessment: 'Gba Iwadi',
    analyzing: 'Nṣe atunyẹwo...',
    
    riskAssessmentResult: 'Abajade Iwadi Ewu',
    confidenceScore: 'Iye Igbagbọ',
    keyFactors: 'Awọn Ohun Pataki Ewu',
    recommendations: 'Awọn Imọran',
    
    lowRisk: 'Ewu Kere',
    mediumRisk: 'Ewu Alabọde',
    highRisk: 'Ewu Giga',
    lowRiskDesc: 'Awọn aami iye rẹ wa laarin awọn iye ilera. Tẹsiwaju awọn ayẹwo ti o yẹ.',
    mediumRiskDesc: 'Diẹ ninu awọn ohun nilo aṣikánya. Ṣeto ìfọ̀rọ̀wánilẹ́nuwò laipẹ.',
    highRiskDesc: 'Itọju iṣoogun ni kia kia ni a ṣe igbesẹ. Kan si olupese ilera rẹ.',
    
    futureMonitoring: 'Ojo iwaju Atunyẹwo',
    wearablesSubtitle: 'Awọn ẹrọ ti a lọwọ ti o ni aṣa Afrika fun atunyẹwo ilera ìyá ti o tẹsiwaju',
    guardianWatch: 'Guardian Watch',
    unityBand: 'Unity Band',
    serenityNecklace: 'Serenity Necklace',
    vitalityRing: 'Vitality Ring',
    keyFeatures: 'Awọn Ẹya Pataki',
    comingSoon: 'Nbo Laipẹ',
    
    connectExperts: 'So pọ mọ Awọn Olùmọ̀',
    telemedicineSubtitle: 'Wiwọle ni kia kia si awọn onímọ ẹ̀kọ́ ilera ìyá ti a fọwọsí',
    ourDoctors: 'Awọn Olupese Ilera Wa',
    bookAppointment: 'Bukuu Appointment',
    available: 'Wa',
    unavailable: 'Ko wa',
    nextAvailable: 'Itele ti o wa',
    viewProfile: 'Wo Profaili',
    specialty: 'Iṣẹ́ ọwọ',
    rating: 'Iye',
    reviews: 'awọn ibeere',
    
    educationTitle: 'Eko Ilera Iya',
    nutrition: 'Ounje & Diet',
    exercise: 'Iṣẹ ẹṣẹ & Fitness',
    mentalHealth: 'Ileru Okàn',
    prenatalCare: 'Itoju Prenatal',
    postnatalCare: 'Itoju Postnatal',
    newbornCare: 'Itoju Ọmọ Tuntun',
    readMore: 'Ka Diẹ Sii',
    
    welcomeBack: 'Kaabo Padà',
    signInToContinue: 'Wọle lati tẹsiwaju irin ajo ilera ìyá rẹ',
    email: 'Adirẹsi Imẹlì',
    password: 'Ọrọigbaniwọle',
    phone: 'Nọmba Foonu',
    name: 'Orukọ Pipe',
    forgotPassword: 'Gbagbe Ọrọigbaniwọle?',
    orContinueWith: 'Tàbí tẹsiwaju pẹlu',
    signInWithGoogle: 'Wọle pẹlu Google',
    noAccount: 'Ko ni àkọlé?',
    haveAccount: 'Ti ni àkọlé tẹlẹ?',
    createAccount: 'Ṣẹda Àkọlé',
    
    myProfile: 'Profaili Mi',
    personalInfo: 'Alaye ti ara ẹni',
    pregnancyInfo: 'Alaye Alaboyun',
    assessmentHistory: 'Itan Iwadi',
    myAppointments: 'Awọn Appointment Mi',
    editProfile: 'Ṣatunkọ Profaili',
    saveChanges: 'Fipamọ Awọn Yipada',
    
    dashboard: 'Dasibodu',
    users: 'Awọn olumulo',
    records: 'Awọn igbasilẹ',
    doctors: 'Awọn dókítà',
    addDoctor: 'Fi Dókítà kun',
    editDoctor: 'Ṣatunkọ Dókítà',
    deleteDoctor: 'Pa Dókítà Rẹ',
    
    footerTagline: 'Olùbátan ilera ìyá alágbára AI ti o fun awọn ìyá ni agbara ni Afrika ati kákiri.',
    quickLinks: 'Awọn Ọna Asopọ Kíákíá',
    resources: 'Awọn orisun',
    contact: 'Kan si',
    rights: 'Gbogbo ẹtọ wa ni a daabobo bo.',
    
    whatMothersSay: 'Ohun ti Awọn Iya Sọ',
    commonQuestions: 'Awọn Ibeere Gbogbogbo',
    
    startToday: 'Bẹrọ Irin Ajo Rẹ Loni',
    ctaSubtitle: 'Dara pọ mọ awọn ìyá ẹgbẹgbẹru ti o ni igbagbọ ninu MamaCare fun irin ajo ilera ìyá wọn',
    downloadApp: 'Gba MamaCare',
    
    // Emergency
    emergency: 'Iṣẹlẹ',
    emergencyTitle: 'Awọn Iṣẹ Iṣẹlẹ',
    emergencySubtitle: 'Gba iranlọwọ ni kia kia',
    requestAmbulance: 'Bẹrẹ Ambulance',
    ambulanceDesc: 'Ipo rẹ yoo ṣe pọ si awọn iṣẹ iṣẹlẹ',
    requesting: 'Nibẹrẹ...',
    callAmbulance: 'Pe Ambulance Bayi',
    emergencyContacts: 'Awọn Olubasọrọ Iṣẹlẹ',
    note: 'Akiyesi',
    emergencyNote: 'Ni ọran ti iṣẹlẹ ti o le fa ikú, pe nọmba iṣẹlẹ agbegbe rẹ ni kia kia.',
  },
  
  // Hausa
  ha: {
    home: 'Gida',
    features: 'Abubuwa',
    assessment: 'Kimar Barazana',
    devices: "Na'urorin",
    telemedicine: 'Telemedicine',
    education: 'Cibiyar Ilimi',
    login: 'Shiga',
    register: 'Yi Rajista',
    logout: 'Fita',
    profile: 'Bayani',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Mai taimakawa lafiya na uwa tare da AI',
    heroBody: 'Bai wa kowace uwa ikon tare da kimiyya barazana, shawarwari na musamman, da goyon baya 24/7 a cikin tafiyar uwa.',
    startJourney: 'Fara Tafiyarka',
    learnMore: 'Kara Koyi',
    
    aiAccuracy: 'Daidaiton AI',
    languages: 'Harsuna',
    support: 'Goyon baya',
    
    comprehensiveCare: 'Kula Duka',
    careSubtitle: 'Duk abin da kuke bukata don lafiyar ciki',
    aiAssessment: 'Kimar Barazana AI',
    aiAssessmentDesc: 'Binciken alamun rai a lokaci gaskiya amfani da tsarin koyon inji LightGBM mai ci gaba',
    telemedicineTitle: 'Telemedicine',
    telemedicineDesc: 'Haɗa da masana lafiya na uwa nan take ta hanyar bidiyo ko tattaunawa',
    educationHub: 'Cibiyar Ilimi',
    educationHubDesc: 'Jagororin lafiya na uwa da aka dogara da shaidu, shawarwarin abinci, da shawarwari na musamman',
    
    howItWorks: 'Yadda MamaCare Ke Aiki',
    step1Title: 'Shigar da Alamun Ranku',
    step1Desc: "Shigar da bayanin lafiyarku da hannu ko haɗa da na'urorin da za a iya sanya don lura da ci gaba",
    step2Title: 'Binciken AI',
    step2Desc: 'Tsarinmu LightGBM yana nazarin dalilan barazanar ku tare da daidaito 84% da bayanin SHAP',
    step3Title: 'Samu Fahimta',
    step3Desc: 'Samu shawarwari na musamman, faɗakarwa, da haɗa da masu bayar da lafiya',
    
    checkRisk: 'Duba Matsalar Barazana',
    age: 'Shekaru (shekaru)',
    systolicBP: 'Systolic BP (mmHg)',
    diastolicBP: 'Diastolic BP (mmHg)',
    bloodSugar: 'Sugar jini (mmol/L)',
    bodyTemp: 'Zafin jiki (°C)',
    heartRate: 'Yawan zuciya (bpm)',
    getAssessment: 'Samu Kimar',
    analyzing: 'Ana nazarin...',
    
    riskAssessmentResult: 'Sakamakon Kimar Barazana',
    confidenceScore: 'Matsayin Dogara',
    keyFactors: 'Muhimman Dalilai',
    recommendations: 'Shawarwari',
    
    lowRisk: 'Barazana Karami',
    mediumRisk: 'Barazana Matsakaici',
    highRisk: 'Barazana Manya',
    lowRiskDesc: 'Alamun ranku suna cikin iyakokin lafiya. Ci gaba da duba yadda ya kamata.',
    mediumRiskDesc: 'Wasu abubuwa suna bukatar hankali. Saita tattaunawa da wuri.',
    highRiskDesc: 'An ba da shawarar kulawa ta gaggawa. Tuntuɓi mai ba da lafiyarku.',
    
    futureMonitoring: 'Makon Gaban Lura',
    wearablesSubtitle: "Na'urorin da za a sanya wa alamar Afrika don lura da lafiyar uwa mai ci gaba",
    guardianWatch: 'Guardian Watch',
    unityBand: 'Unity Band',
    serenityNecklace: 'Serenity Necklace',
    vitalityRing: 'Vitality Ring',
    keyFeatures: 'Muhimman Fasalulloli',
    comingSoon: 'Zai zo da Sauri',
    
    connectExperts: 'Haɗa da Masana',
    telemedicineSubtitle: 'Iso mai sauri zuwa masana lafiya na uwa da aka tabbatar',
    ourDoctors: 'Masu Bayar da Lafiyarmu',
    bookAppointment: 'Loda Appointment',
    available: 'Akwai',
    unavailable: 'Babu',
    nextAvailable: 'Na Gaba Akwai',
    viewProfile: 'Duba Bayani',
    specialty: "Sana'a",
    rating: 'Kimantawa',
    reviews: 'bita',
    
    educationTitle: 'Ilimi Lafiya na Uwa',
    nutrition: 'Abinci & Diet',
    exercise: 'Motsa Jiki & Fitness',
    mentalHealth: 'Lafiyar Hankali',
    prenatalCare: 'Kula na Prenatal',
    postnatalCare: 'Kula na Postnatal',
    newbornCare: 'Kula da Sabon Haihuwa',
    readMore: 'Kara Karanta',
    
    welcomeBack: 'Barka da Dawowa',
    signInToContinue: 'Shiga don ci gaba da tafiyar lafiyar uwa',
    email: 'Adireshin Imel',
    password: 'Kalmar Sirri',
    phone: 'Lambar Wayya',
    name: 'Cikakken Suna',
    forgotPassword: 'An manta Kalmar Sirri?',
    orContinueWith: 'Ko ci gaba da',
    signInWithGoogle: 'Shiga da Google',
    noAccount: 'Ba ku da asusu?',
    haveAccount: 'Tuni kuna da asusu?',
    createAccount: 'Kirkiri Asusu',
    
    myProfile: 'Bayanina',
    personalInfo: 'Bayani na Keɗai',
    pregnancyInfo: 'Bayani Ciki',
    assessmentHistory: 'Tarihin Kimar',
    myAppointments: 'Appointment Na',
    editProfile: 'Gyara Bayani',
    saveChanges: 'Adana Canje-canje',
    
    dashboard: 'Dashboard',
    users: 'Masu amfani',
    records: 'Rikodin',
    doctors: 'Likitoci',
    addDoctor: 'Kara Likita',
    editDoctor: 'Gyara Likita',
    deleteDoctor: 'Share Likita',
    
    footerTagline: 'Mai taimakawa lafiya na uwa mai karfi na AI wanda ke ba uwa ikon a Afrika da wajen.',
    quickLinks: 'Haɗin Kai Tsaye',
    resources: "Ma'aunai",
    contact: 'Tuntuɓi',
    rights: 'Duk haƙƙin da aka kiyasta.',
    
    whatMothersSay: 'Abin da Iyaye Ke Cewa',
    commonQuestions: 'Tambayoyin Da Ake Yawan Yi',
    
    startToday: 'Fara Tafiyarku Yau',
    ctaSubtitle: 'Shiga cikin dubban iyaye waɗanda suka dogara da MamaCare don tafiyar lafiyar uwa',
    downloadApp: 'Zazzage MamaCare',
    
    // Emergency
    emergency: 'Gaggawa',
    emergencyTitle: 'Ayyukan Gaggawa',
    emergencySubtitle: 'Samu taimako nan take',
    requestAmbulance: 'Nemi Ambulance',
    ambulanceDesc: 'Wurin ku zai aika wa masu aikin gaggawa',
    requesting: 'Ana nema...',
    callAmbulance: 'Kira Ambulance Yanzu',
    emergencyContacts: 'Lambobin Tuntuɓi na Gaggawa',
    note: 'Lura',
    emergencyNote: 'A cikin yanayin gaggawa da za ta iya kashe ku, kira lambar gaggawar ku nan take.',
  },
  
  // Igbo
  ig: {
    home: 'Ulọ',
    features: 'Ihe ngwọta',
    assessment: 'Nlele Ọrịa',
    devices: 'Ngwaọrụ',
    telemedicine: 'Telemedicine',
    education: 'Ụlọ Ọzụzụ',
    login: 'Banye',
    register: 'Deba aha',
    logout: 'Pụọ',
    profile: 'Profaịlụ',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Enyemaka ahụike nne na AI',
    heroBody: 'Inye ọ bụla nne ike site na nyocha ụgha ọgụgụ isi, ntụziaka pụrụ iche, na nkwado 24/7 site na njem nne.',
    startJourney: 'Bido Ọdịnihu Gị',
    learnMore: 'Mụtakwu',
    
    aiAccuracy: 'Akaụntụ AI',
    languages: 'Asụsụ',
    support: 'Nkwado',
    
    comprehensiveCare: 'Nlekọta Zuru Oke',
    careSubtitle: 'Ihe niile ị chọrọ maka ahụike ime ime',
    aiAssessment: 'Nlele Ọrịa AI',
    aiAssessmentDesc: "Nyocha akara ndụ n'oge gbasara site na iji usoro mmụta igwe LightGBM na-aga n'ihu",
    telemedicineTitle: 'Telemedicine',
    telemedicineDesc: 'Jikọọ na ndị ọkachamara ahụike nne ozugbo site na vidio ma ọ bụ nkata',
    educationHub: 'Ụlọ Ọzụzụ',
    educationHubDesc: 'Ntụziaka ahụike nne dabere na ihe akaebe, ndụmọdụ nri, na ntụziaka pụrụ iche',
    
    howItWorks: 'Ka MamaCare Si Arụ Ọrụ',
    step1Title: 'Tinye Akara Ndụ Gị',
    step1Desc: "Tinye data ahụike gị n'aka ma ọ bụ jikọọ na ngwaọrụ ejiji maka nyocha na-aga n'ihu",
    step2Title: 'Nyocha AI',
    step2Desc: 'Usoro anyị LightGBM na nyocha ihe kpatara ụgha gị na akaụntụ 84% na nkọwa SHAP',
    step3Title: 'Nweta Nghọta',
    step3Desc: 'Nweta ntụziaka pụrụ iche, ịdọ aka ná ntị, na jikọọ na ndị ọrụ ahụike',
    
    checkRisk: 'Lelee Ọkwa Ọrịa',
    age: 'Afọ (afọ)',
    systolicBP: 'Systolic BP (mmHg)',
    diastolicBP: 'Diastolic BP (mmHg)',
    bloodSugar: 'Suga ọbara (mmol/L)',
    bodyTemp: 'Ọkọdọ ahụ (°C)',
    heartRate: 'Ọsọ obi (bpm)',
    getAssessment: 'Nweta Nlele',
    analyzing: 'Na-anya...',
    
    riskAssessmentResult: 'Nsonaazụ Nlele Ọrịa',
    confidenceScore: 'Akara Ncheta',
    keyFactors: 'Ihe Kpatara Pụrụ Iche',
    recommendations: 'Nduọ',
    
    lowRisk: 'Ọrịa Dị ala',
    mediumRisk: 'Ọrịa Dị etiti',
    highRisk: 'Ọrịa Dị elu',
    lowRiskDesc: "Akara ndụ gị nọ n'etiti akara ahụike. Nọgide na nyocha dị ka o kwesịghị.",
    mediumRiskDesc: "Ihe ụfọdụ chọrọ ntị. Hazi mkparịta ụka n'oge adịghị anya.",
    highRiskDesc: "A tụrụ aro nlekọta ọnwụ n'oge adịghị anya. Kpọtụrụ onye na-enye gị ahụike.",
    
    futureMonitoring: 'Ọdịnihu Nlele',
    wearablesSubtitle: "Ngwaọrụ ejiji ejiji Africa maka nlele ahụike nne na-aga n'ihu",
    guardianWatch: 'Guardian Watch',
    unityBand: 'Unity Band',
    serenityNecklace: 'Serenity Necklace',
    vitalityRing: 'Vitality Ring',
    keyFeatures: 'Ihe Ndị Pụrụ Iche',
    comingSoon: "Na-abịa N'oge Adịghị Anyaa",
    
    connectExperts: 'Jikọọ na Ndị Ọkachamara',
    telemedicineSubtitle: 'Nweta ozugbo na ndị ọkachamara ahụike nne a kwadoro',
    ourDoctors: 'Ndị Ọrụ Ahụike Anyị',
    bookAppointment: 'Debe Appointment',
    available: 'Dị',
    unavailable: 'Adịghị',
    nextAvailable: 'Na-esote Dị',
    viewProfile: 'Lelee Profaịlụ',
    specialty: 'Ọrụ aka',
    rating: 'Ntughari',
    reviews: 'nyocha',
    
    educationTitle: 'Mmụta Ahụike Nne',
    nutrition: 'Nri & Diet',
    exercise: 'Mmezu & Fitness',
    mentalHealth: 'Ahụike Mmetụta Uche',
    prenatalCare: 'Nlekọta Prenatal',
    postnatalCare: 'Nlekọta Postnatal',
    newbornCare: 'Nlekọta Ọmụma',
    readMore: 'Gụkwuo',
    
    welcomeBack: 'Nnọọ Ozọ',
    signInToContinue: 'Banye iji nọgide na njem ahụike nne gị',
    email: 'Adreesị Email',
    password: 'Okwuntughe',
    phone: 'Nọmba Ekwentị',
    name: 'Aha Nzuzo',
    forgotPassword: 'Chefuru Okwuntughe?',
    orContinueWith: 'Ma ọ bụ nọgide na',
    signInWithGoogle: 'Banye na Google',
    noAccount: 'Ị nweghị akaụntụ?',
    haveAccount: 'Ị nwere akaụntụ?',
    createAccount: 'Mepụta Akaụntụ',
    
    myProfile: 'Profaịlụ M',
    personalInfo: 'Ozi Onwe Onye',
    pregnancyInfo: 'Ozi Imere Me',
    assessmentHistory: 'Akụkọ Ihe Nlele',
    myAppointments: 'Appointment M',
    editProfile: 'Dezie Profaịlụ',
    saveChanges: 'Chekwaa Ọzọ',
    
    dashboard: 'Dashboard',
    users: 'Ndị ọrụ',
    records: 'Rekọọdụ',
    doctors: 'Ndị dọkịta',
    addDoctor: 'Tinye Dọkịta',
    editDoctor: 'Dezie Dọkịta',
    deleteDoctor: 'Hichapụ Dọkịta',
    
    footerTagline: "Enyemaka ahụike nne na AI na-aga nke ọma na-enye ndị nne ike na Africa na n'ihu.",
    quickLinks: 'Njikọ ọsọ ọsọ',
    resources: 'Ihe Eji Enye',
    contact: 'Kpọtụrụ',
    rights: 'Echekwara ikike niile.',
    
    whatMothersSay: 'Ihe Ndị Nne Na-ekwu',
    commonQuestions: 'Ajụjụ Ndị A Na-ajụkarị',
    
    startToday: 'Bido Ọdịnihu Gị Taa',
    ctaSubtitle: 'Jikọọ na ọtụtụ puku ndị nne kwere na MamaCare maka njem ahụike nne ha',
    downloadApp: 'Budata MamaCare',
    
    // Emergency
    emergency: 'Ihe Mberede',
    emergencyTitle: 'Ọrụ Ihe Mberede',
    emergencySubtitle: 'Nweta enyemaka ozugbo',
    requestAmbulance: 'Rọ Ambulance',
    ambulanceDesc: 'Ebe ị nọ ga-ekesa ndị ọrụ ihe mberede',
    requesting: 'Na-arọ...',
    callAmbulance: 'Kpọ Ambulance Ugbu a',
    emergencyContacts: 'Kpọtụrụ Ihe Mberede',
    note: 'Mara',
    emergencyNote: "N'ihe mberede nwere ike ịbụ ọnwụ, kpọ nọmba ihe mberede obodo gị ozugbo.",
  },
  
  // Fulfude (Fulfulde)
  ff: {
    home: 'Saare',
    features: 'Fannuuji',
    assessment: 'Ƴiyya Risiq',
    devices: 'Kaɓe',
    telemedicine: 'Telemedicine',
    education: 'Pinal Debbo',
    login: 'Seeno',
    register: 'Winndito',
    logout: 'Yaltu',
    profile: 'Profail',
    admin: 'Admin Dashboard',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Kefal AI moƴƴere rewbe',
    heroBody: 'Rewɓe fuu ɓe keƴƴitina hakkillaaji, ƴiyya risiq, dokkal 24/7 e nguurndam rewbe.',
    startJourney: 'Fuɗɗo Nguurndam Ma',
    learnMore: 'Ɓeydu Humpito',
    
    aiAccuracy: 'Doole AI',
    languages: 'Ɗemɗe',
    support: 'Ballal',
    mothersHelped: 'Rewɓe Ballaaɓe',
    
    comprehensiveCare: 'Kefal Yonnde',
    careSubtitle: 'Ko fuu ko cokli ngam rewde moƴƴere',
    aiAssessment: 'Ƴiyya Risiq AI',
    aiAssessmentDesc: 'Ƴiyya ƴiƴam e waktu fuu huutoraade LightGBM',
    telemedicineTitle: 'Telemedicine',
    telemedicineDesc: 'Seŋo e doktoreeji rewbe e waktu fuu',
    educationHub: 'Pinal Debbo',
    educationHubDesc: 'Ekkitaaji dokkal rewbe, nguurndam, ekkitaaji',
    
    howItWorks: 'No MamaCare Gollortoo',
    step1Title: 'Naatnu Ɗiƴam Ma',
    step1Desc: 'Naatnu dokkal ma walla seŋo kaɓe ma',
    step2Title: 'Ƴiyya AI',
    step2Desc: 'LightGBM ɗon ƴiya dokkal ma doole 84%',
    step3Title: 'Heɓ Humpito',
    step3Desc: 'Heɓ dokkal, jeertine, seŋo e doktoreeji',
    
    checkRisk: 'Ƴiyya Risiq Ma',
    assessmentSubtitle: 'Naatnu ƴiƴam ma ngam ƴiyya risiq',
    age: 'Duuɓi (dooɓi)',
    systolicBP: 'Systolic BP (mmHg)',
    diastolicBP: 'Diastolic BP (mmHg)',
    bloodSugar: 'Sukari ƴiiƴam (mmol/L)',
    bodyTemp: 'Ɓuurnaangal (°C)',
    heartRate: 'Yonnde ɓerɗe (bpm)',
    getAssessment: 'Ƴiyya',
    analyzing: 'Ƴiyya...',
    
    currentSymptoms: 'Cuuɗi Waktu',
    selectSymptoms: 'Suɓo cuuɗi ɗi njogii',
    additionalNotes: 'Ɓeyditte Goɗɗe',
    
    riskAssessmentResult: 'Jaltugal Ƴiyya Risiq',
    confidenceScore: 'Doole Ƴiyya',
    keyFactors: 'Cuuɗi Mawɗi',
    recommendations: 'Dokkale',
    normalRange: 'Ɗiƴam fuu ɗon ley dokkal',
    
    lowRisk: 'Risiq Ɓuuɗɗum',
    mediumRisk: 'Risiq Hakkunde',
    highRisk: 'Risiq Mawɗo',
    lowRiskDesc: 'Ɗiƴam ma ɗon ley dokkal. Tokkito ƴiyya.',
    mediumRiskDesc: 'Ɓeydite cokli hakkilantaagal. Yillo dokto.',
    highRiskDesc: 'Dokkal jaawɗo cokli. Taw dokto ma.',
    
    aiModelInsights: 'Humpito AI (SHAP)',
    bloodSugarImportance: 'Sukari ƴiiƴam - Dokkal risiq mawɗo',
    ageImportance: 'Duuɓi - Duuɓi rewde naƴata nguurndam',
    heartRateImportance: 'Yonnde ɓerɗe - Ƴiyya dokkal ɓerɗe',
    
    pastAssessments: 'Ƴiyyaaji Ɓennuɗi',
    noPastAssessments: 'Alaa Ƴiyyaaji Ɓennuɗi',
    
    futureMonitoring: 'Waktu Goɗngu',
    wearablesSubtitle: 'Kaɓe Afrika ngam ƴiyya rewbe',
    guardianWatch: 'Guardian Watch',
    guardianWatchDesc: 'Ƴiyya ƴiƴam fuu waktu',
    unityBand: 'Unity Band',
    unityBandDesc: 'Ƴiyya gollal e ɗaakal',
    serenityNecklace: 'Serenity Necklace',
    serenityNecklaceDesc: 'Ƴiyya doole e jam',
    vitalityRing: 'Vitality Ring',
    vitalityRingDesc: 'Ƴiyya dokkal fuu waktu',
    keyFeatures: 'Fannuuji Mawɗi',
    comingSoon: 'Nane',
    
    connectExperts: 'Seŋo e Doktoreeji',
    telemedicineSubtitle: 'Heɓ doktoreeji rewbe e waktu fuu',
    videoConsult: 'Haalnde Vidiyo',
    videoConsultDesc: 'Haalnde dokto ma e galle ma',
    chatSupport: 'Ballal Chat',
    chatSupportDesc: 'Ballal 24/7 ngam ƴamde',
    appointmentBooking: 'Book Appointment',
    appointmentBookingDesc: 'Book dokto ma e no ɓuri weeɓde',
    ourDoctors: 'Doktoreeji Amen',
    bookAppointment: 'Book Appointment',
    available: 'Heɓii',
    unavailable: 'Heɓaani',
    nextAvailable: 'Heɓii Waktu Goɗngu',
    viewProfile: 'Yiy Profail',
    specialty: 'Gollal',
    languagesSpoken: 'Ɗemɗe',
    rating: 'Ƴiyya',
    reviews: 'Ƴiyyaaji',
    
    educationTitle: 'Ekkita Dokkal Rewbe',
    educationSubtitle: 'Ekkitaaji dokkal rewbe e nguurndam',
    nutrition: 'Nguurndam & Liiɗi',
    exercise: 'Gollal & Doole',
    mentalHealth: 'Dokkal Bana',
    prenatalCare: 'Kefal Kisaaka',
    postnatalCare: 'Kefal Caggal Danygol',
    newbornCare: 'Kefal Ɗanygol Keso',
    readMore: 'Ɓeydu',
    
    welcomeBack: 'A jaɓɓaama',
    signInToContinue: 'Seeno ngam tokkittingo',
    email: 'Email',
    password: 'Finnde',
    phone: 'Telfon',
    name: 'Innde',
    forgotPassword: 'Finnde Yejjitaa?',
    orContinueWith: 'Walla fuɗɗo e',
    signInWithGoogle: 'Seeno e Google',
    signInWithPhone: 'Seeno e Telfon',
    noAccount: 'A alaa konte?',
    haveAccount: 'Aɗa jogii konte?',
    createAccount: 'Sos Konte',
    agreeTerms: 'Mi jaɓɓii Sartaaji',
    
    myProfile: 'Profail Am',
    personalInfo: 'Humpito Ma',
    pregnancyInfo: 'Humpito Rewde',
    assessmentHistory: 'Ƴiyyaaji Ɓennuɗi',
    myAppointments: 'Appointments Am',
    editProfile: 'Waylu Profail',
    saveChanges: 'Dannu Waylude',
    dueDate: 'Bana Danygol',
    bloodType: 'Fannu ƴiiƴam',
    allergies: 'Cuuɗi',
    medications: 'Gazaki',
    
    dashboard: 'Dashboard',
    users: 'Huutorɓe',
    records: 'Winndaaɗi',
    doctors: 'Doktoreeji',
    content: 'Loowdi',
    settings: 'Teelte',
    totalUsers: 'Huutorɓe Fuu',
    totalAssessments: 'Ƴiyyaaji Fuu',
    totalDoctors: 'Doktoreeji Fuu',
    totalAppointments: 'Appointments Fuu',
    riskDistribution: 'Risiqji',
    recentActivity: 'Gollal Ɓennuɗo',
    addDoctor: 'Ɓeydu Dokto',
    editDoctor: 'Waylu Dokto',
    deleteDoctor: 'Ittu Dokto',
    
    footerTagline: 'Kefal AI moƴƴere rewbe e Afrika e nokkuuji goɗɗi.',
    quickLinks: 'Jokke Ɓurɗe Weeɓde',
    resources: 'Loowdi',
    contact: 'Jokkondir',
    supportEmail: 'support@mamacare.app',
    supportPhone: '+234 800 MAMACARE',
    location: 'Lagos, Nigeria',
    rights: 'Yamiroore fuu ko amen.',
    researchBy: 'Ƴiyya Idris Olanrewaju Ibraheem',
    
    whatMothersSay: 'Ko Rewɓe Ngi\'i',
    commonQuestions: 'Ƴamde Ɓurɗe Yottude',
    
    startToday: 'Fuɗɗo Haa Jooni',
    ctaSubtitle: 'Seŋo e rewɓe ujunaaji ɗiɗi ɓe koolii MamaCare',
    downloadApp: 'Aawto MamaCare',
    
    // Emergency
    emergency: 'Dokkal Jaawɗo',
    emergencyTitle: 'Dokkale Jaawɗo',
    emergencySubtitle: 'Heɓ ballal jaawɗo',
    requestAmbulance: 'Ƴaame Ambulance',
    ambulanceDesc: 'Nokku ma yottinte dokkale jaawɗo',
    requesting: 'Ƴaamoo...',
    callAmbulance: 'Noddu Ambulance Jooni',
    emergencyContacts: 'Jokkondirɓe Jaawɗo',
    note: 'Humpito',
    emergencyNote: 'So aɗa jogii dokkal jaawɗo, noddu nokku dokkal jaawɗo ma jaawɗo.',
  },
  
  // Swahili
  sw: {
    home: 'Nyumbani',
    features: 'Vipengele',
    assessment: 'Tathmini ya Hatari',
    devices: 'Vifaa',
    telemedicine: 'Telemedicine',
    education: 'Kituo cha Elimu',
    login: 'Ingia',
    register: 'Jisajili',
    logout: 'Toka',
    profile: 'Wasifu',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Msaada wa kiafya wa mama ukitumia AI',
    heroBody: 'Kuwapa kila mama nguvu kwa tathmini ya hatari ya akili, mwongozo wa kibinafsi, na usaidizi wa 24/7 katika safari ya uzazi.',
    startJourney: 'Anza Safari Yako',
    learnMore: 'Jifunze Zaidi',
    
    aiAccuracy: 'Ukweli wa AI',
    languages: 'Lugha',
    support: 'Msaada',
    
    comprehensiveCare: 'Huduma Kamili',
    careSubtitle: 'Kila kitu unachohitaji kwa ajili ya ujauzito mzima',
    aiAssessment: 'Tathmini ya Hatari ya AI',
    aiAssessmentDesc: 'Uchanganuzi wa alama za uhai kwa wakati halisi ukitumia mifumo ya kujifunza kwa mashine ya LightGBM',
    telemedicineTitle: 'Telemedicine',
    telemedicineDesc: 'Unganishwa na wataalamu wa afya ya mama mara moja kupitia video au mazungumzo',
    educationHub: 'Kituo cha Elimu',
    educationHubDesc: 'Miongozo ya afya ya mama iliyothibitishwa na ushahidi, vidokezo vya lishe, na mapendekezo ya kibinafsi',
    
    howItWorks: 'Mamacare Inavyofanya Kazi',
    step1Title: 'Weka Alama Zako za Uhai',
    step1Desc: 'Weka data yako ya afya kwa mkono au unganisha na vifaa vya kuvaa kwa ufuatiliaji endelevu',
    step2Title: 'Uchanganuzi wa AI',
    step2Desc: 'Mfumo wetu wa LightGBM huchanganua visababishi vya hatari vyako kwa usahihi wa 84% na uelewa wa SHAP',
    step3Title: 'Pata Uchunguzi',
    step3Desc: 'Pokea mapendekezo ya kibinafsi, arifa, na uunganishwe na watoa huduma za afya',
    
    checkRisk: 'Angalia Kiwango Chako cha Hatari',
    age: 'Umri (miaka)',
    systolicBP: 'Systolic BP (mmHg)',
    diastolicBP: 'Diastolic BP (mmHg)',
    bloodSugar: 'Sukari ya Damu (mmol/L)',
    bodyTemp: 'Joto la Mwili (°C)',
    heartRate: 'Kiwango cha Moyo (bpm)',
    getAssessment: 'Pata Tathmini',
    analyzing: 'Inachanganua...',
    
    riskAssessmentResult: 'Matokeo ya Tathmini ya Hatari',
    confidenceScore: 'Kiwango cha Imani',
    keyFactors: 'Visababishi Muhimu vya Hatari',
    recommendations: 'Mapendekezo',
    
    lowRisk: 'Hatari Ndogo',
    mediumRisk: 'Hatari ya Wastani',
    highRisk: 'Hatari Kubwa',
    lowRiskDesc: 'Alama zako za uhai ziko ndani ya viwango vya afya. Endelea na ukaguzi wa kawaida.',
    mediumRiskDesc: 'Baadhi ya mambo yanahitaji tahadhari. Panga mazungumzo hivi karibuni.',
    highRiskDesc: 'Matibabu ya dharura yapendekezwa. Wasiliana na mtoa huduma yako wa afya.',
    
    futureMonitoring: 'Mustakabali wa Ufuatiliaji',
    wearablesSubtitle: 'Vifaa vya kuvaa vya Afrika kwa ufuatiliaji endelevu wa afya ya mama',
    guardianWatch: 'Guardian Watch',
    unityBand: 'Unity Band',
    serenityNecklace: 'Serenity Necklace',
    vitalityRing: 'Vitality Ring',
    keyFeatures: 'Vipengele Muhimu',
    comingSoon: 'Inakuja Hivi Karibuni',
    
    connectExperts: 'Unganishwa na Wataalamu',
    telemedicineSubtitle: 'Ufikiaji wa haraka kwa wataalamu wa afya ya mama walioidhinishwa',
    ourDoctors: 'Watoa Huduma Wetu wa Afya',
    bookAppointment: 'Weka Kikao',
    available: 'Inapatikana',
    unavailable: 'Haipatikani',
    nextAvailable: 'Inayofuata Inapatikana',
    viewProfile: 'Tazama Wasifu',
    specialty: 'Utaalamu',
    rating: 'Ukadiriaji',
    reviews: 'hakiki',
    
    educationTitle: 'Elimu ya Afya ya Mama',
    nutrition: 'Lishe & Mlo',
    exercise: 'Mazoezi & Fitness',
    mentalHealth: 'Afya ya Akili',
    prenatalCare: 'Huduma ya Kabla ya Kujifungua',
    postnatalCare: 'Huduma ya Baada ya Kujifungua',
    newbornCare: 'Huduma ya Mtoto Mchanga',
    readMore: 'Soma Zaidi',
    
    welcomeBack: 'Karibu Tena',
    signInToContinue: 'Ingia ili kuendelea na safari yako ya afya ya mama',
    email: 'Anwani ya Barua Pepe',
    password: 'Nenosiri',
    phone: 'Nambari ya Simu',
    name: 'Jina Kamili',
    forgotPassword: 'Umesahau Nenosiri?',
    orContinueWith: 'Au endelea na',
    signInWithGoogle: 'Ingia na Google',
    noAccount: 'Huna akaunti?',
    haveAccount: 'Tayari una akaunti?',
    createAccount: 'Unda Akaunti',
    
    myProfile: 'Wasifu Wangu',
    personalInfo: 'Taarifa za Kibinafsi',
    pregnancyInfo: 'Taarifa za Ujauzito',
    assessmentHistory: 'Historia ya Tathmini',
    myAppointments: 'Mikango Yangu',
    editProfile: 'Hariri Wasifu',
    saveChanges: 'Hifadhi Mabadiliko',
    
    dashboard: 'Dashibodi',
    users: 'Watumiaji',
    records: 'Rekodi',
    doctors: 'Madaktari',
    addDoctor: 'Ongeza Daktari',
    editDoctor: 'Hariri Daktari',
    deleteDoctor: 'Futa Daktari',
    
    footerTagline: 'Msaada wa kiafya wa mama ukitumia AI unaowapa mama nguvu Afrika na zaidi.',
    quickLinks: 'Viungo vya Haraka',
    resources: 'Rasilimali',
    contact: 'Wasiliana',
    rights: 'Haki zote zimehifadhiwa.',
    
    whatMothersSay: 'Wazazi Wanasema Nini',
    commonQuestions: 'Maswali Yanayoulizwa Mara kwa Mara',
    
    startToday: 'Anza Safari Yako Leo',
    ctaSubtitle: 'Jiunge na mama elfu wanaoamini MamaCare kwa safari yao ya afya ya mama',
    downloadApp: 'Pakua MamaCare',
    
    // Emergency
    emergency: 'Dharura',
    emergencyTitle: 'Huduma za Dharura',
    emergencySubtitle: 'Pata msaada mara moja',
    requestAmbulance: 'Omba Ambulance',
    ambulanceDesc: 'Mahali ulipo litashirikiwa na huduma za dharura',
    requesting: 'Inaomba...',
    callAmbulance: 'Piga Ambulance Sasa',
    emergencyContacts: 'Mawasiliano ya Dharura',
    note: 'Kumbuka',
    emergencyNote: 'Ikiwa ni dharura inayoweza kusababisha kifo, piga namba yako ya dharura mara moja.',
  },
  
  // French
  fr: {
    home: 'Accueil',
    features: 'Fonctionnalités',
    assessment: 'Évaluation des Risques',
    devices: 'Appareils Portables',
    telemedicine: 'Télémédecine',
    education: 'Centre d\'Éducation',
    login: 'Connexion',
    register: 'S\'inscrire',
    logout: 'Déconnexion',
    profile: 'Profil',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Compagnon de santé maternelle alimenté par IA',
    heroBody: 'Donner à chaque mère les moyens d\'agir grâce à une évaluation intelligente des risques, des conseils personnalisés et un soutien 24h/24 tout au long du parcours de maternité.',
    startJourney: 'Commencez Votre Voyage',
    learnMore: 'En Savoir Plus',
    
    aiAccuracy: 'Précision IA',
    languages: 'Langues',
    support: 'Support',
    
    comprehensiveCare: 'Soins Complets',
    careSubtitle: 'Tout ce dont vous avez besoin pour une grossesse en bonne santé',
    aiAssessment: 'Évaluation des Risques IA',
    aiAssessmentDesc: 'Analyse en temps réel des signes vitaux utilisant des modèles d\'apprentissage automatique LightGBM avancés',
    telemedicineTitle: 'Télémédecine',
    telemedicineDesc: 'Connectez-vous instantanément avec des spécialistes de la santé maternelle via vidéo ou chat',
    educationHub: 'Centre d\'Éducation',
    educationHubDesc: 'Guides de santé maternelle fondés sur des preuves, conseils nutritionnels et recommandations personnalisées',
    
    howItWorks: 'Comment Fonctionne MamaCare',
    step1Title: 'Entrez Vos Signes Vitaux',
    step1Desc: 'Saisissez vos données de santé manuellement ou connectez-vous à des appareils portables pour un suivi continu',
    step2Title: 'Analyse IA',
    step2Desc: 'Notre modèle LightGBM analyse vos facteurs de risque avec 84% de précision et explicabilité SHAP',
    step3Title: 'Obtenez des Insights',
    step3Desc: 'Recevez des recommandations personnalisées, des alertes et connectez-vous avec des professionnels de santé',
    
    checkRisk: 'Vérifiez Votre Niveau de Risque',
    age: 'Âge (années)',
    systolicBP: 'Pression Systolique (mmHg)',
    diastolicBP: 'Pression Diastolique (mmHg)',
    bloodSugar: 'Glycémie (mmol/L)',
    bodyTemp: 'Température Corporelle (°C)',
    heartRate: 'Fréquence Cardiaque (bpm)',
    getAssessment: 'Obtenir l\'Évaluation',
    analyzing: 'Analyse en cours...',
    
    riskAssessmentResult: 'Résultat de l\'Évaluation des Risques',
    confidenceScore: 'Score de Confiance',
    keyFactors: 'Facteurs Clés de Risque',
    recommendations: 'Recommandations',
    
    lowRisk: 'Risque Faible',
    mediumRisk: 'Risque Moyen',
    highRisk: 'Risque Élevé',
    lowRiskDesc: 'Vos signes vitaux sont dans des plages saines. Continuez les contrôles réguliers.',
    mediumRiskDesc: 'Certains facteurs nécessitent attention. Planifiez une consultation bientôt.',
    highRiskDesc: 'Attention médicale immédiate recommandée. Contactez votre professionnel de santé.',
    
    futureMonitoring: 'Avenir du Suivi',
    wearablesSubtitle: 'Appareils portables africains conceptuels pour le suivi continu de la santé maternelle',
    guardianWatch: 'Guardian Watch',
    unityBand: 'Unity Band',
    serenityNecklace: 'Serenity Necklace',
    vitalityRing: 'Vitality Ring',
    keyFeatures: 'Caractéristiques Clés',
    comingSoon: 'Bientôt Disponible',
    
    connectExperts: 'Connectez-vous avec des Experts',
    telemedicineSubtitle: 'Accès instantané à des spécialistes de la santé maternelle certifiés',
    ourDoctors: 'Nos Professionnels de Santé',
    bookAppointment: 'Prendre Rendez-vous',
    available: 'Disponible',
    unavailable: 'Indisponible',
    nextAvailable: 'Prochaine Disponibilité',
    viewProfile: 'Voir le Profil',
    specialty: 'Spécialité',
    rating: 'Évaluation',
    reviews: 'avis',
    
    educationTitle: 'Éducation Santé Maternelle',
    nutrition: 'Nutrition & Régime',
    exercise: 'Exercice & Fitness',
    mentalHealth: 'Santé Mentale',
    prenatalCare: 'Soins Prénataux',
    postnatalCare: 'Soins Postnataux',
    newbornCare: 'Soins du Nouveau-né',
    readMore: 'Lire la Suite',
    
    welcomeBack: 'Bon Retour',
    signInToContinue: 'Connectez-vous pour continuer votre parcours de santé maternelle',
    email: 'Adresse Email',
    password: 'Mot de Passe',
    phone: 'Numéro de Téléphone',
    name: 'Nom Complet',
    forgotPassword: 'Mot de Passe Oublié?',
    orContinueWith: 'Ou continuez avec',
    signInWithGoogle: 'Connexion avec Google',
    noAccount: 'Pas de compte?',
    haveAccount: 'Déjà un compte?',
    createAccount: 'Créer un Compte',
    
    myProfile: 'Mon Profil',
    personalInfo: 'Informations Personnelles',
    pregnancyInfo: 'Informations de Grossesse',
    assessmentHistory: 'Historique des Évaluations',
    myAppointments: 'Mes Rendez-vous',
    editProfile: 'Modifier le Profil',
    saveChanges: 'Enregistrer les Modifications',
    
    dashboard: 'Tableau de Bord',
    users: 'Utilisateurs',
    records: 'Dossiers',
    doctors: 'Médecins',
    addDoctor: 'Ajouter un Médecin',
    editDoctor: 'Modifier le Médecin',
    deleteDoctor: 'Supprimer le Médecin',
    
    footerTagline: 'Compagnon de santé maternelle IA donnant du pouvoir aux mères en Afrique et au-delà.',
    quickLinks: 'Liens Rapides',
    resources: 'Ressources',
    contact: 'Contact',
    rights: 'Tous droits réservés.',
    
    whatMothersSay: 'Ce que Disent les Mères',
    commonQuestions: 'Questions Fréquentes',
    
    startToday: 'Commencez Votre Voyage Aujourd\'hui',
    ctaSubtitle: 'Rejoignez des milliers de mères qui font confiance à MamaCare pour leur parcours de santé maternelle',
    downloadApp: 'Télécharger MamaCare',
    
    // Emergency
    emergency: 'Urgence',
    emergencyTitle: 'Services d\'Urgence',
    emergencySubtitle: 'Obtenez de l\'aide immédiatement',
    requestAmbulance: 'Demander une Ambulance',
    ambulanceDesc: 'Votre position sera partagée avec les services d\'urgence',
    requesting: 'Demande en cours...',
    callAmbulance: 'Appeler l\'Ambulance Maintenant',
    emergencyContacts: 'Contacts d\'Urgence',
    note: 'Note',
    emergencyNote: 'En cas d\'urgence mettant la vie en danger, appelez immédiatement votre numéro d\'urgence local.',
  },
  
  // Portuguese
  pt: {
    home: 'Início',
    features: 'Recursos',
    assessment: 'Avaliação de Risco',
    devices: 'Dispositivos',
    telemedicine: 'Telemedicina',
    education: 'Centro de Educação',
    login: 'Entrar',
    register: 'Cadastrar',
    logout: 'Sair',
    profile: 'Perfil',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Companheiro de saúde materna com IA',
    heroBody: 'Capacitando cada mãe com avaliação inteligente de riscos, orientação personalizada e suporte 24/7 ao longo da jornada da maternidade.',
    startJourney: 'Comece Sua Jornada',
    learnMore: 'Saiba Mais',
    
    aiAccuracy: 'Precisão da IA',
    languages: 'Idiomas',
    support: 'Suporte',
    
    comprehensiveCare: 'Cuidado Completo',
    careSubtitle: 'Tudo o que você precisa para uma gravidez saudável',
    aiAssessment: 'Avaliação de Risco com IA',
    aiAssessmentDesc: 'Análise em tempo real dos sinais vitais usando modelos avançados de aprendizado de máquina LightGBM',
    telemedicineTitle: 'Telemedicina',
    telemedicineDesc: 'Conecte-se instantaneamente com especialistas em saúde materna via vídeo ou chat',
    educationHub: 'Centro de Educação',
    educationHubDesc: 'Guias de saúde materna baseados em evidências, dicas nutricionais e recomendações personalizadas',
    
    howItWorks: 'Como Funciona o MamaCare',
    step1Title: 'Insira Seus Sinais Vitais',
    step1Desc: 'Insira seus dados de saúde manualmente ou conecte-se a dispositivos vestíveis para monitoramento contínuo',
    step2Title: 'Análise de IA',
    step2Desc: 'Nosso modelo LightGBM analisa seus fatores de risco com 84% de precisão e explicabilidade SHAP',
    step3Title: 'Obtenha Insights',
    step3Desc: 'Receba recomendações personalizadas, alertas e conecte-se com profissionais de saúde',
    
    checkRisk: 'Verifique Seu Nível de Risco',
    age: 'Idade (anos)',
    systolicBP: 'Pressão Sistólica (mmHg)',
    diastolicBP: 'Pressão Diastólica (mmHg)',
    bloodSugar: 'Glicemia (mmol/L)',
    bodyTemp: 'Temperatura Corporal (°C)',
    heartRate: 'Frequência Cardíaca (bpm)',
    getAssessment: 'Obter Avaliação',
    analyzing: 'Analisando...',
    
    riskAssessmentResult: 'Resultado da Avaliação de Risco',
    confidenceScore: 'Pontuação de Confiança',
    keyFactors: 'Fatores Chave de Risco',
    recommendations: 'Recomendações',
    
    lowRisk: 'Risco Baixo',
    mediumRisk: 'Risco Médio',
    highRisk: 'Risco Alto',
    lowRiskDesc: 'Seus sinais vitais estão dentro de faixas saudáveis. Continue com check-ups regulares.',
    mediumRiskDesc: 'Alguns fatores precisam de atenção. Agende uma consulta em breve.',
    highRiskDesc: 'Atenção médica imediata recomendada. Entre em contato com seu profissional de saúde.',
    
    futureMonitoring: 'Futuro do Monitoramento',
    wearablesSubtitle: 'Dispositivos vestíveis conceituais com tema africano para monitoramento contínuo da saúde materna',
    guardianWatch: 'Guardian Watch',
    unityBand: 'Unity Band',
    serenityNecklace: 'Serenity Necklace',
    vitalityRing: 'Vitality Ring',
    keyFeatures: 'Principais Recursos',
    comingSoon: 'Em Breve',
    
    connectExperts: 'Conecte-se com Especialistas',
    telemedicineSubtitle: 'Acesso instantâneo a especialistas certificados em saúde materna',
    ourDoctors: 'Nossos Profissionais de Saúde',
    bookAppointment: 'Agendar Consulta',
    available: 'Disponível',
    unavailable: 'Indisponível',
    nextAvailable: 'Próxima Disponibilidade',
    viewProfile: 'Ver Perfil',
    specialty: 'Especialidade',
    rating: 'Avaliação',
    reviews: 'avaliações',
    
    educationTitle: 'Educação em Saúde Materna',
    nutrition: 'Nutrição & Dieta',
    exercise: 'Exercício & Fitness',
    mentalHealth: 'Saúde Mental',
    prenatalCare: 'Cuidado Pré-natal',
    postnatalCare: 'Cuidado Pós-natal',
    newbornCare: 'Cuidado com o Recém-nascido',
    readMore: 'Leia Mais',
    
    welcomeBack: 'Bem-vinda de Volta',
    signInToContinue: 'Entre para continuar sua jornada de saúde materna',
    email: 'Endereço de Email',
    password: 'Senha',
    phone: 'Número de Telefone',
    name: 'Nome Completo',
    forgotPassword: 'Esqueceu a Senha?',
    orContinueWith: 'Ou continue com',
    signInWithGoogle: 'Entrar com Google',
    noAccount: 'Não tem conta?',
    haveAccount: 'Já tem conta?',
    createAccount: 'Criar Conta',
    
    myProfile: 'Meu Perfil',
    personalInfo: 'Informações Pessoais',
    pregnancyInfo: 'Informações da Gravidez',
    assessmentHistory: 'Histórico de Avaliações',
    myAppointments: 'Minhas Consultas',
    editProfile: 'Editar Perfil',
    saveChanges: 'Salvar Alterações',
    
    dashboard: 'Painel',
    users: 'Usuários',
    records: 'Registros',
    doctors: 'Médicos',
    addDoctor: 'Adicionar Médico',
    editDoctor: 'Editar Médico',
    deleteDoctor: 'Excluir Médico',
    
    footerTagline: 'Companheiro de saúde materna com IA capacitando mães na África e além.',
    quickLinks: 'Links Rápidos',
    resources: 'Recursos',
    contact: 'Contato',
    rights: 'Todos os direitos reservados.',
    
    whatMothersSay: 'O que as Mães Dizem',
    commonQuestions: 'Perguntas Frequentes',
    
    startToday: 'Comece Sua Jornada Hoje',
    ctaSubtitle: 'Junte-se a milhares de mães que confiam no MamaCare para sua jornada de saúde materna',
    downloadApp: 'Baixar MamaCare',
    
    // Emergency
    emergency: 'Emergência',
    emergencyTitle: 'Serviços de Emergência',
    emergencySubtitle: 'Obtenha ajuda imediatamente',
    requestAmbulance: 'Solicitar Ambulância',
    ambulanceDesc: 'Sua localização será compartilhada com os serviços de emergência',
    requesting: 'Solicitando...',
    callAmbulance: 'Ligar para Ambulância Agora',
    emergencyContacts: 'Contatos de Emergência',
    note: 'Nota',
    emergencyNote: 'Em caso de emergência que coloque a vida em risco, ligue imediatamente para o número de emergência local.',
  },
  
  // Arabic
  ar: {
    home: 'الرئيسية',
    features: 'الميزات',
    assessment: 'تقييم المخاطر',
    devices: 'الأجهزة',
    telemedicine: 'الطب عن بعد',
    education: 'مركز التعليم',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    
    heroTitle: 'ماماكير',
    heroSubtitle: 'رفيق صحة الأم بالذكاء الاصطناعي',
    heroBody: 'تمكين كل أم بتقييم ذكي للمخاطر، وإرشادات شخصية، ودعم على مدار الساعة طوال رحلة الأمومة.',
    startJourney: 'ابدأي رحلتك',
    learnMore: 'اعرفي المزيد',
    
    aiAccuracy: 'دقة الذكاء الاصطناعي',
    languages: 'اللغات',
    support: 'الدعم',
    
    comprehensiveCare: 'رعاية شاملة',
    careSubtitle: 'كل ما تحتاجينه لحمل صحي',
    aiAssessment: 'تقييم المخاطر بالذكاء الاصطناعي',
    aiAssessmentDesc: 'تحليل فوري للعلامات الحيوية باستخدام نماذج التعلم الآلي المتقدمة LightGBM',
    telemedicineTitle: 'الطب عن بعد',
    telemedicineDesc: 'تواصلي فوراً مع أخصائيي صحة الأم عبر الفيديو أو الدردشة',
    educationHub: 'مركز التعليم',
    educationHubDesc: 'أدلة صحة الأم المبنية على الأدلة، نصائح غذائية، وتوصيات شخصية',
    
    howItWorks: 'كيف تعمل ماماكير',
    step1Title: 'أدخلي علاماتك الحيوية',
    step1Desc: 'أدخلي بيانات صحتك يدوياً أو اتصلي بأجهزة قابلة للارتداء للمراقبة المستمرة',
    step2Title: 'التحليل بالذكاء الاصطناعي',
    step2Desc: 'نموذجنا LightGBM يحلل عوامل الخطر بنسبة دقة 84% مع تفسير SHAP',
    step3Title: 'احصلي على رؤى',
    step3Desc: 'احصلي على توصيات شخصية وتنبيهات وتواصلي مع مقدمي الرعاية الصحية',
    
    checkRisk: 'تحققي من مستوى المخاطر',
    age: 'العمر (سنوات)',
    systolicBP: 'ضغط الدم الانقباضي (ملم زئبق)',
    diastolicBP: 'ضغط الدم الانبساطي (ملم زئبق)',
    bloodSugar: 'سكر الدم (ميلي مول/لتر)',
    bodyTemp: 'درجة حرارة الجسم (°م)',
    heartRate: 'معدل ضربات القلب (نبضة/دقيقة)',
    getAssessment: 'احصلي على التقييم',
    analyzing: 'جاري التحليل...',
    
    riskAssessmentResult: 'نتيجة تقييم المخاطر',
    confidenceScore: 'درجة الثقة',
    keyFactors: 'عوامل الخطر الرئيسية',
    recommendations: 'التوصيات',
    
    lowRisk: 'مخاطر منخفضة',
    mediumRisk: 'مخاطر متوسطة',
    highRisk: 'مخاطر عالية',
    lowRiskDesc: 'علاماتك الحيوية ضمن المعدلات الصحية. استمري بالفحوصات الدورية.',
    mediumRiskDesc: 'بعض العوامل تحتاج اهتماماً. حددي موعد استشارة قريباً.',
    highRiskDesc: 'يوصى بالاهتمام الطبي الفوري. تواصلي مع مقدم الرعاية الصحية.',
    
    futureMonitoring: 'مستقبل المراقبة',
    wearablesSubtitle: 'أجهزة قابلة للارتداء بأفريقية الطابع للمراقبة المستمرة لصحة الأم',
    guardianWatch: 'ساعة الحارس',
    unityBand: 'سوار الوحدة',
    serenityNecklace: 'عقد الهدوء',
    vitalityRing: 'خاتم الحيوية',
    keyFeatures: 'الميزات الرئيسية',
    comingSoon: 'قريباً',
    
    connectExperts: 'تواصلي مع الخبراء',
    telemedicineSubtitle: 'وصول فوري إلى أخصائيي صحة الأم المعتمدين',
    ourDoctors: 'مقدمو الرعاية الصحية لدينا',
    bookAppointment: 'حجز موعد',
    available: 'متاح',
    unavailable: 'غير متاح',
    nextAvailable: 'الموعد المتاح التالي',
    viewProfile: 'عرض الملف الشخصي',
    specialty: 'التخصص',
    rating: 'التقييم',
    reviews: 'تقييم',
    
    educationTitle: 'تعليم صحة الأم',
    nutrition: 'التغذية والنظام الغذائي',
    exercise: 'الرياضة واللياقة',
    mentalHealth: 'الصحة النفسية',
    prenatalCare: 'الرعاية قبل الولادة',
    postnatalCare: 'الرعاية بعد الولادة',
    newbornCare: 'رعاية المولود الجديد',
    readMore: 'اقرأي المزيد',
    
    welcomeBack: 'مرحباً بعودتك',
    signInToContinue: 'سجلي الدخول للاستمرار في رحلة صحة الأم',
    email: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    phone: 'رقم الهاتف',
    name: 'الاسم الكامل',
    forgotPassword: 'نسيتي كلمة المرور؟',
    orContinueWith: 'أو استمرري باستخدام',
    signInWithGoogle: 'تسجيل الدخول بجوجل',
    noAccount: 'ليس لديك حساب؟',
    haveAccount: 'لديك حساب بالفعل؟',
    createAccount: 'إنشاء حساب',
    
    myProfile: 'ملفي الشخصي',
    personalInfo: 'المعلومات الشخصية',
    pregnancyInfo: 'معلومات الحمل',
    assessmentHistory: 'سجل التقييمات',
    myAppointments: 'مواعيدي',
    editProfile: 'تعديل الملف الشخصي',
    saveChanges: 'حفظ التغييرات',
    
    dashboard: 'لوحة التحكم',
    users: 'المستخدمون',
    records: 'السجلات',
    doctors: 'الأطباء',
    addDoctor: 'إضافة طبيب',
    editDoctor: 'تعديل الطبيب',
    deleteDoctor: 'حذف الطبيب',
    
    footerTagline: 'رفيق صحة الأم بالذكاء الاصطناعي يمكّن الأمهات في أفريقيا وما وراءها.',
    quickLinks: 'روابط سريعة',
    resources: 'الموارد',
    contact: 'اتصال',
    rights: 'جميع الحقوق محفوظة.',
    
    whatMothersSay: 'ماذا تقول الأمهات',
    commonQuestions: 'الأسئلة الشائعة',
    
    startToday: 'ابدأي رحلتك اليوم',
    ctaSubtitle: 'انضمي إلى آلاف الأمهات اللواتي يثقن بماماكير لرحلة صحة الأم',
    downloadApp: 'حمّلي ماماكير',
    
    // Emergency
    emergency: 'طوارئ',
    emergencyTitle: 'خدمات الطوارئ',
    emergencySubtitle: 'احصلي على المساعدة فوراً',
    requestAmbulance: 'اطلبي الإسعاف',
    ambulanceDesc: 'سيتم مشاركة موقعك مع خدمات الطوارئ',
    requesting: 'جاري الطلب...',
    callAmbulance: 'اتصلي بالإسعاف الآن',
    emergencyContacts: 'جهات اتصال الطوارئ',
    note: 'ملاحظة',
    emergencyNote: 'في حالة طوارئ تهدد الحياة، اتصلي برقم الطوارئ المحلي فوراً.',
  },
  
  // Zulu
  zu: {
    home: 'Ikhaya',
    features: 'Izici',
    assessment: 'Ukuhlola Ubungozi',
    devices: 'Amathuluzi',
    telemedicine: 'Telemedicine',
    education: 'Isikhungo Sokufunda',
    login: 'Ngena',
    register: 'Bhalisa',
    logout: 'Phuma',
    profile: 'Iphrofayela',
    
    heroTitle: 'Mamacare',
    heroSubtitle: 'Umsizi wezempilo kamama osebenzisa u-AI',
    heroBody: 'Sinikeza wonke mama amandla ngokuhlola ubungozi obuhlakaniphile, isiqondiso esihlukile, nasekusekelweni 24/7 kulo lonke uhambo lokuba ngumama.',
    startJourney: 'Qala Uhwago Lwakho',
    learnMore: 'Funda Kabanzi',
    
    aiAccuracy: 'Ukunemba kwe-AI',
    languages: 'Izilimi',
    support: 'Amasupport',
    
    comprehensiveCare: 'Ukunakekela Okugcwele',
    careSubtitle: 'Konke okudingekayo ukuze ukhulelwe kahle',
    aiAssessment: 'Ukuhlola Ubungozi kwe-AI',
    aiAssessmentDesc: 'Ukuhlaziywa kwamaphuzu aphilayo ngesikhathi sokuqondile usebenzisa amamodeli afundileyo emshini we-LightGBM',
    telemedicineTitle: 'Telemedicine',
    telemedicineDesc: 'Xhumana ngokushesha nabochwepheshe bezempilo kamama ngevidiyo noma ingxoxo',
    educationHub: 'Isikhungo Sokufunda',
    educationHubDesc: 'Iziqondiso zezempilo kamama ezisekelwe ebufakazini, iziluleko zokudla, neziphakamiso ezihlukile',
    
    howItWorks: 'Mamacare Isebenza Kanjani',
    step1Title: 'Faka Amaphuzu Akho Aphilayo',
    step1Desc: 'Faka idatha yakho yezempilo ngesandla noma uxhumane namathuluzi okugqoka ukuze uhlolwe ngokugcwele',
    step2Title: 'Ukuhlaziywa kwe-AI',
    step2Desc: 'Imodeli yethu ye-LightGBM ihlaziya izici zobungozi bakho ngenkulu ukunemba kwe-84% nokuqondwa kwe-SHAP',
    step3Title: 'Thola Ukuqonda',
    step3Desc: 'Thola iziphakamiso ezihlukile, izaziso, futhi uxhumane nabahlinzeki bezempilo',
    
    checkRisk: 'Hlola Izinga Lobungozi Bakho',
    age: 'Iminyaka (iminyaka)',
    systolicBP: 'Systolic BP (mmHg)',
    diastolicBP: 'Diastolic BP (mmHg)',
    bloodSugar: 'Ushukela eGazini (mmol/L)',
    bodyTemp: 'Ukushisa Komzimba (°C)',
    heartRate: 'Izinga Lenhliziyo (bpm)',
    getAssessment: 'Thola Ukuhlolwa',
    analyzing: 'Ihlaziya...',
    
    riskAssessmentResult: 'Imiphumela Yokuhlola Ubungozi',
    confidenceScore: 'Izinga Lokuthemba',
    keyFactors: 'Izici Ezibalulekile Zobungozi',
    recommendations: 'Iziphakamiso',
    
    lowRisk: 'Ubungozi Obuphansi',
    mediumRisk: 'Ubungozi Ongaphakathi',
    highRisk: 'Ubungozi Obuphezulu',
    lowRiskDesc: 'Amaphuzu akho aphilayo asemkhawulweni wezempilo. Qhubeka nokuhlola okujwayelekile.',
    mediumRiskDesc: 'Ezinye izidingo zidinga ukunakwa. Hlela inkulumo-mpendulofuthi.',
    highRiskDesc: 'Kunconywa ukunakekelwa kwesibhedlela ngokushesha. Xhumana nomhlinzeki wakho wezempilo.',
    
    futureMonitoring: 'Ikusasa Lokuhlola',
    wearablesSubtitle: 'Amathuluzi okugqoka ase-Afrika okuhlola izempilo kamama ngokugcwele',
    guardianWatch: 'Guardian Watch',
    unityBand: 'Unity Band',
    serenityNecklace: 'Serenity Necklace',
    vitalityRing: 'Vitality Ring',
    keyFeatures: 'Izici Ezibalulekile',
    comingSoon: 'Izayo Ngokushesha',
    
    connectExperts: 'Xhumana Nabochwepheshe',
    telemedicineSubtitle: 'Ukufinyelela ngokushesha kubochwepheshe bezempilo kamama abaqinisekisiwe',
    ourDoctors: 'Abahlinzeki Bethu Bezempilo',
    bookAppointment: 'Bhoka Ithikithi',
    available: 'Iyatholakala',
    unavailable: 'Ayitholakali',
    nextAvailable: 'Okulandelayo Kuyatholakala',
    viewProfile: 'Buka Iphrofayela',
    specialty: 'Ispecialti',
    rating: 'Isilinganiso',
    reviews: 'ukubuyekeza',
    
    educationTitle: 'Umfundo Wezempilo Kamama',
    nutrition: 'Ukudla & Idayethi',
    exercise: 'Imizamo & Fitness',
    mentalHealth: 'Impilo Engqondweni',
    prenatalCare: 'Ukunakekela Ngaphambi Kokubeletha',
    postnatalCare: 'Ukunakekela Ngemuva Kokubeletha',
    newbornCare: 'Ukunakekela Kwezingane Ezintsha',
    readMore: 'Funda Kabanzi',
    
    welcomeBack: 'Siyakwamukela',
    signInToContinue: 'Ngena ukuze uqhubele phambili uhambo lwakho lwezempilo kamama',
    email: 'Ikheli Le-imeyili',
    password: 'Iphasiwedi',
    phone: 'Inombolo Yocingo',
    name: 'Igama Eligcwele',
    forgotPassword: 'Ukhohlwe Iphasiwedi?',
    orContinueWith: 'Noma qhubeka nge',
    signInWithGoogle: 'Ngena nge-Google',
    noAccount: 'Awunayo i-akhawunti?',
    haveAccount: 'Usuvenile i-akhawunti?',
    createAccount: 'Dala I-akhawunti',
    
    myProfile: 'Iphrofayela Yami',
    personalInfo: 'Ulwazi Lomuntu Siqu',
    pregnancyInfo: 'Ulwazi Lokukhulelwa',
    assessmentHistory: 'Umlando Wokuhlola',
    myAppointments: 'Amathikithi Ami',
    editProfile: 'Hlela Iphrofayela',
    saveChanges: 'Londoloza Izinguquko',
    
    dashboard: 'Ideshibhodi',
    users: 'Abasebenzisi',
    records: 'Amarekhodi',
    doctors: 'Odotela',
    addDoctor: 'Engeza Udotela',
    editDoctor: 'Hlela Udotela',
    deleteDoctor: 'Susa Udotela',
    
    footerTagline: 'Umsizi wezempilo kamama osebenzisa u-AI onikeza amandla amama e-Afrika naphesheya.',
    quickLinks: 'Izixhumanisi Ezisheshayo',
    resources: 'Izinsiza',
    contact: 'Xhumana',
    rights: 'Onke amalungelo agodliwe.',
    
    whatMothersSay: 'Okushiwyo Ngamama',
    commonQuestions: 'Imibuzo Ejwayelekile',
    
    startToday: 'Qala Uhwago Lwakho Namuhla',
    ctaSubtitle: 'Joyina amama ayizinkulungwane akholelwa ku-Mamacare ngehwago lwawo lwezempilo kamama',
    downloadApp: 'Landa MamaCare',
    
    // Emergency
    emergency: 'Isimo Esiphuthumayo',
    emergencyTitle: 'Izinsiza Zesimo Esiphuthumayo',
    emergencySubtitle: 'Thola usizo ngokushesha',
    requestAmbulance: 'Cela I-Ambulance',
    ambulanceDesc: 'Indawo yakho izokwabiwa nezinsiza zesimo esiphuthumayo',
    requesting: 'Iyacela...',
    callAmbulance: 'Shaya I-Ambulance Manje',
    emergencyContacts: 'Oxhumana Nabo Ngesimo Esiphuthumayo',
    note: 'Qaphela',
    emergencyNote: 'Uma kunesimo esiphuthumayo esingabulala, shaya inombolo yakho yesimo esiphuthumayo ngokushesha.',
  },
};

interface LanguageContextType {
  currentLang: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLang, setCurrentLang] = useState('en');

  const setLanguage = useCallback((lang: string) => {
    setCurrentLang(lang);
    // Store in localStorage
    localStorage.setItem('mamacare-language', lang);
    // Update HTML dir for Arabic
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, []);

  // Load saved language on mount
  React.useEffect(() => {
    const saved = localStorage.getItem('mamacare-language');
    if (saved && translations[saved]) {
      setCurrentLang(saved);
      document.documentElement.dir = saved === 'ar' ? 'rtl' : 'ltr';
    }
  }, []);

  const t = useCallback((key: string): string => {
    const langTranslations = translations[currentLang] || translations['en'];
    return langTranslations[key] || translations['en'][key] || key;
  }, [currentLang]);

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
